language: php

php:
  - 5.5
  - 5.4
  - 5.3
  - hhvm
  
env:
  - DB=mysql
  
before_script:
  - travis_retry composer self-update
  - travis_retry composer install --prefer-source --no-interaction --dev
  - chmod -R 777 cache
  - mysql -e 'create database myapp_test;'
  - mysql myapp_test < install/index.php?action=install&step=2;
  
  
services:
  - memcached
  
script:
  
matrix:
  allow_failures:
    - php: hhvm
  fast_finish: true
